Added version command and release script for github actions
topicuskeyhub/aws-keyhub pull request #21
Opened 2021-10-29 13:29 UTC by ChristianHersevoort

2021-11-01 15:23 UTC, vincentheet requested changes

2021-11-01 15:23 UTC, vincentheet commented on cmd/version.go
> +		logrus.Infoln(fmt.Sprintf("Version %s (hash: %s, go version: %s)", GitTag, GitHash, GoVersion))
Zou je hier niet de logrus Infof functie kunnen gebruiken?

2021-11-01 15:23 UTC, vincentheet commented on .github/workflows/release.yml
> +  Relase-tag:
Release-tag

2021-11-12 14:31 UTC, ChristianHersevoort commented on cmd/version.go
> +		logrus.Infoln(fmt.Sprintf("Version %s (hash: %s, go version: %s)", GitTag, GitHash, GoVersion))
done

2021-11-12 14:33 UTC, vincentheet approved these changes

2021-11-12 14:33 UTC, merged